# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170302_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoddata',
            name='observer',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
