# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_demoddata_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='tle1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='satellite',
            name='tle2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
