# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-06 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170323_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='status',
            field=models.CharField(choices=[(b'a', b'Alive'), (b'd', b'Dead'), (b'r', b'Re-Entered')], default=b'a', max_length=2),
        ),
    ]
