# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170323_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='status',
            field=models.CharField(choices=[(b'alive', b'alive'), (b'dead', b'dead'), (b're-entered', b're-entered')], default=b'alive', max_length=10),
        ),
    ]
