# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_satellite_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
