# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20170407_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmitter',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
